# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
DISABLE_LINTERS:
  - JAVASCRIPT_PRETTIER
  - JSON_PRETTIER
  - TYPESCRIPT_PRETTIER
  - YAML_PRETTIER
  - TERRAFORM_TERRASCAN
DISABLE_ERRORS_LINTERS:
  - SPELL_LYCHEE
  - SPELL_CSPELL
PRINT_ALL_FILES: false
# FILTER_REGEX_EXCLUDE: '(\.cspell\.json|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
# REPOSITORY_TRIVY_ARGUMENTS:
#   - "--skip-dirs"
#   - ".devcontainer"
#   - "--skip-dirs"
#   - ".github"
#   - "--skip-dirs"
#   - ".terraform"
REPOSITORY_KICS_ARGUMENTS:
  - "--fail-on"
  - "high,medium"
JSON_JSONLINT_ARGUMENTS:
  - "--no-duplicate-keys"
  - "--trailing-newline"
  - "--comments"
FLAVOR_SUGGESTIONS: true
