---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      # check-json can't cope with JSON with comments
      # - id: check-json
      - id: check-shebang-scripts-are-executable
      # pretty-format-json can't cope with JSON with comments
      # - id: pretty-format-json
        # args: ["--autofix"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/AleksaC/terraform-py
    rev: v1.9.8
    hooks:
      - id: tf-fmt
      - id: tf-validate

# CI to run pre-commit and maintain the repo
ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false
